<?xml version="1.0" encoding="utf-8"?><Database Name="DB_HCGS_ASSET_KPT" Class="DC_AMKODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PABBAPCO401\sqlexpress;Initial Catalog=DB_HCGS_ASSET_KPT;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="ASSET.TBL_R_CONDITION" Member="TBL_R_CONDITIONs">
    <Type Name="TBL_R_CONDITION">
      <Column Name="COND_CODE" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COND_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.TBL_R_DEPT" Member="TBL_R_DEPTs">
    <Type Name="TBL_R_DEPT">
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DEPT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.TBL_R_MERK" Member="TBL_R_MERKs">
    <Type Name="TBL_R_MERK">
      <Column Name="MERK_CODE" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MERK_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.TBL_R_TYPE_ASSET" Member="TBL_R_TYPE_ASSETs">
    <Type Name="TBL_R_TYPE_ASSET">
      <Column Name="TYPE_CODE" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TYPE_NAME" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.TBL_R_LOCATION" Member="TBL_R_LOCATIONs">
    <Type Name="TBL_R_LOCATION">
      <Column Name="LOCATION_CODE" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LOCATION_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.TBL_T_HISTORY_ASSET" Member="TBL_T_HISTORY_ASSETs">
    <Type Name="TBL_T_HISTORY_ASSET">
      <Column Name="PID_HISTORI" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ASSET_NUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HISTORY_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LOCATION_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KARYAWAN" Member="VW_KARYAWANs">
    <Type Name="VW_KARYAWAN">
      <Column Name="Nrp" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Nama" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TempatLahir" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TglLahir" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JenisKelamin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GolonganDarah" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="StatusKawin" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Agama" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Pendidikan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AlamatTinggal" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Jamsostek" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DPA" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="TglMasukPama" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TglPensiun" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Golongan" Type="System.String" DbType="VarChar(53)" CanBeNull="true" />
      <Column Name="TglPromosi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDJabatan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="JABATAN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TglMutasi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StatusKeluarga" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="StatusBawaKeluarga" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TglBawaKeluarga" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Departemen" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="StatusPenerimaan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="POH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Gaji" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RateUlap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Telepon" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Lokasi" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Approve" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SisaCutiPeriode1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SisaCutiPeriode2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SisaCutiBesar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OnSite" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Rekening" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="KodeBank" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="StatusPekerjaan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RewardSarana" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Harike7" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SisaUangObat" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SHE_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SHE_Group" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OCR_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OCR_Group" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MasaDinas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ellipse" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Mess" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.VW_HISTORY" Member="VW_HISTORies">
    <Type Name="VW_HISTORY">
      <Column Name="PID_HISTORI" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HISTORY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ASSET_NUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ASSET_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LOCATION_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCATION_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COND_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="COND_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PIC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PIC_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.TBL_M_ASSET" Member="TBL_M_ASSETs">
    <Type Name="TBL_M_ASSET">
      <Column Name="PID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ASSET_NUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ASSET_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ASSET_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ST_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MERK_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TYPE_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NO_PR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PIC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ORDER_BY" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COND_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LOCATION_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IMG" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.VW_ASSET" Member="VW_ASSETs">
    <Type Name="VW_ASSET">
      <Column Name="PID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ASSET_NUMBER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ASSET_NAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ASSET_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ST_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MERK_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TYPE_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TYPE_NAME" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NO_PR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PIC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PIC_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEPT_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEPT_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ORDER_BY" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ORDER_BY_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COND_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="COND_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCATION_CODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCATION_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LAMA_ASSET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IMG" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="ASSET.VW_DASHBOARD" Member="VW_DASHBOARDs">
    <Type Name="VW_DASHBOARD">
      <Column Name="TAHUN" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="BULAN" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="BULAN_DESC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TOTAL_ASSET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_AMOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="ASSET.SP_DELETE_ASSET" Method="SP_DELETE_ASSET">
    <Parameter Name="ASSET_NUMBER" Parameter="aSSET_NUMBER" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="ASSET.SP_TRANS_ASSET" Method="SP_TRANS_ASSET">
    <Parameter Name="ASSET_NUMBER" Parameter="aSSET_NUMBER" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ASSET_NAME" Parameter="aSSET_NAME" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ASSET_DATE" Parameter="aSSET_DATE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ST_DATE" Parameter="sT_DATE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MERK_CODE" Parameter="mERK_CODE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="SN" Parameter="sN" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TYPE_CODE" Parameter="tYPE_CODE" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="NO_PR" Parameter="nO_PR" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PIC" Parameter="pIC" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="DEPT_CODE" Parameter="dEPT_CODE" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ORDER_BY" Parameter="oRDER_BY" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="AMOUNT" Parameter="aMOUNT" Type="System.Int32" DbType="Int" />
    <Parameter Name="COND_CODE" Parameter="cOND_CODE" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="LOCATION_CODE" Parameter="lOCATION_CODE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="REMARK" Parameter="rEMARK" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IMG" Parameter="iMG" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="TRANS_STATUS" Parameter="tRANS_STATUS" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
</Database>